#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=03:00
#SBATCH --account=sadasivan
#SBATCH --partition=mi1004x

# The application(s) to execute along with its input arguments and options:

# if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
#     echo "Usage: ./run_tests {program}"
#     exit 1
# fi

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH

if ! [[ "$1" =~ ^[0-9]+$ ]]; then
  echo "Invalid number. Please give a valid number"
  exit 1
fi

echo "Running the project $1 times..."
./build project.cu project_build

for (( i=1; i<=$1; i++ ))
do
    echo "Run - $i"
    epoch_time1=$(date +%s)
    ./project_build
    epoch_time2=$(date +%s)
    difference=$((epoch_time2 - epoch_time1))

    echo "Time taken for run - $i in seconds - $difference"


done
rm project_build
