#!/bin/bash
# The interpreter used to execute the script

#“#SBATCH” directives that convey submission options:

#SBATCH --job-name=example_job
#SBATCH --mail-type=BEGIN,END
#SBATCH --nodes=1
#SBATCH --ntasks-per-node=1
#SBATCH --time=03:00
#SBATCH --account=sadasivan
#SBATCH --partition=devel

# The application(s) to execute along with its input arguments and options:

if [ "$#" -ne 1 ] && [ "$#" -ne 2 ]; then
    echo "Usage: ./run_tests {program}"
    echo "Usage: ./run_tests {program} {test_number}"
    exit 1
fi

export LD_LIBRARY_PATH=$PWD/libwb/build/:$LD_LIBRARY_PATH

if [ "$#" -eq  1 ]; then
    SCORE=0
    TOTAL=0
    for test in test-dtw/*; do
        ((++TOTAL))
        if diff <(./$1 -e $test/output_dtw.raw -i $test/query.raw,$test/reference.raw -o $test/attempt.raw -t matrix | tail -1) <(echo The solution is correct) &>/dev/null; 
        then
            ((++SCORE))
            echo "Passed $test!"
        else
            echo "$test is incorrect..."
        fi
    done

    echo "$SCORE/$TOTAL tests passed"
fi

if [ "$#" -eq  2 ]; then
    ./$1 -e test-dtw/$2/output_dtw.raw -i test-dtw/$2/query.raw,test-dtw/$2/reference.raw -o test-dtw/$2/attempt.raw -t matrix
fi
